int32 id_previous

int32 direction

bool north_blocked
bool east_blocked
bool south_blocked
bool west_blocked

bool object_here
int32 object_type
float32 object_x
float32 object_y

---

Node generated_node
